[project]
name = "taipy-wine-app"
version = "0.1.0"
description = "A Taipy dashboard application showing wine production data."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.2",
    "taipy>=4.1.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]
