
[DATA_NODE.WINE_PRODUCTION]
storage_type = "csv"
default_path = "data/wine_harvest_france_aoc_09_19.csv"
scope = "SCENARIO:SCOPE"

[TASK.ADD_WINE_STATS]
inputs = ["WINE_PRODUCTION:SECTION"]
outputs = ["WINE_PRODUCTION_WITH_STATS:SECTION"]
function = "config.functions.add_basic_stats:function"
skippable = "False:bool"

[DATA_NODE.WINE_PRODUCTION_WITH_STATS]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.ADD_GEOMETRY]
inputs = ["WINE_PRODUCTION_WITH_STATS:SECTION", "GEOMETRY:SECTION"]
outputs = ["WINE_PRODUCTION_WITH_GEOMETRY:SECTION"]
function = "config.functions.add_geometry:function"
skippable = "False:bool"

[DATA_NODE.WINE_PRODUCTION_WITH_GEOMETRY]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.GEOMETRY]
storage_type = "json"
default_path = "data/french_wine_bassin_centroids.geojson"
scope = "SCENARIO:SCOPE"

[SCENARIO.SC_WINE]
additional_data_nodes = [ ]
tasks = [ "ADD_WINE_STATS:SECTION", "ADD_GEOMETRY:SECTION" ]
